services:
    edit_content:
         class: Tgc\EditContentBundle\Service\EditContent
         arguments: ["@session","@doctrine.orm.default_entity_manager"]

    EditContentBundle\EventSubscriber\LocaleSubscriber:
        arguments: ['%kernel.default_locale%']
