<?php

namespace tgc\EditContentBundle\Repository;

/**
 * TextEditableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextEditableRepository extends \Doctrine\ORM\EntityRepository
{
}
